import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider, SignIn, SignInButton, SignedIn, SignedOut, UserButton } from "@clerk/nextjs";
import AuthWrapper from "@/components/authwrapper";
import { ToastProvider } from "@/components/providers/toaster-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          {/* <header className="flex justify-between">
            <p className="text-xl">LMS Project</p>
            <UserButton />
          </header> */}
          {/* <UserButton /> */}
          {/* <SignedOut>
            <SignIn routing="hash" />
          </SignedOut>
          <SignedIn>
            {children}
          </SignedIn> */}
          <AuthWrapper>
            <ToastProvider />
            {children}
          </AuthWrapper>
        </body>
      </html>
    </ClerkProvider>
  );
}
